apiVersion: v1
kind: Secret
metadata:
  name: soul-mirror-kubeconfig
  labels:
  {{- include "sm.labels" . | nindent 4 }}
data:
  {{- $this := .}}
  {{- range $key, $val := .Values.config.kubeconfig}}
  {{$val}}: |-
    {{- $path:= printf "config/%s" $val}}
    {{ $this.Files.Get $path|b64enc | indent 4 }}
  {{- end}}