apiVersion: v1
kind: ServiceAccount
metadata:
  name: soul-mirror
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: soul-mirror
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: soul-mirror
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: soul-mirror
subjects:
  - kind: ServiceAccount
    name: soul-mirror
    namespace: {{.Release.Namespace}}