# Default values for girls.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: registry.baidubce.com/apps/platform/soul-mirror
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.

config:
  kubeconfig:
    - dev
    - dev2
  loglevel: info

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 1000m
    memory: 2048Mi

nodeSelector: {}

tolerations: []

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: service-offline
              operator: In
              values:
                - "on"